// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppD0keueLQXdYN6nKW2TGJw5aGenbJ2E',
    appId: '1:519612206948:web:4c0057db614d2e17be3471',
    messagingSenderId: '519612206948',
    projectId: 'rps-flutter-firebase',
    authDomain: 'rps-flutter-firebase.firebaseapp.com',
    storageBucket: 'rps-flutter-firebase.firebasestorage.app',
    measurementId: 'G-1FYMBGV85N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPD3WUIPLBmRz1NzEME38I-d3feMMwhXg',
    appId: '1:519612206948:android:de169146ef56f81bbe3471',
    messagingSenderId: '519612206948',
    projectId: 'rps-flutter-firebase',
    storageBucket: 'rps-flutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxQIqIjQdXu-ggZ8ZR9xRsU-1ntj6TjE',
    appId: '1:519612206948:ios:ca15108f1c8709cbbe3471',
    messagingSenderId: '519612206948',
    projectId: 'rps-flutter-firebase',
    storageBucket: 'rps-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.rpsFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxQIqIjQdXu-ggZ8ZR9xRsU-1ntj6TjE',
    appId: '1:519612206948:ios:ca15108f1c8709cbbe3471',
    messagingSenderId: '519612206948',
    projectId: 'rps-flutter-firebase',
    storageBucket: 'rps-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.rpsFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDppD0keueLQXdYN6nKW2TGJw5aGenbJ2E',
    appId: '1:519612206948:web:1e8962f7f352bbfdbe3471',
    messagingSenderId: '519612206948',
    projectId: 'rps-flutter-firebase',
    authDomain: 'rps-flutter-firebase.firebaseapp.com',
    storageBucket: 'rps-flutter-firebase.firebasestorage.app',
    measurementId: 'G-S7ZQ399TLK',
  );
}
